# Generated by Django 4.0.1 on 2022-06-28 06:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_id', models.EmailField(max_length=50, unique=True)),
                ('account_name', models.CharField(max_length=50)),
                ('app_secret_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('website', models.CharField(max_length=50)),
            ],
        ),
    ]
